Pull requests changes
gersilex/apcupsd-docker pull request #4
Opened 2020-09-13 20:54 UTC by cassiorossi

Hi Leroy, as you suggested, here is my pull request so you can review the code and understand better my changes.

In general, my motivation was to 
1. Listen all UPS trigger instead of only shutdown event  - in order to handle it I used the netcat utility (docker-->host communication);
2. Reuse my existing acpupsd scripts (using the same name) - in order to handle it I changed the host-trigger-check.sh to call an script with the same name of the UPS event
3. Created a script to start, stop and rebuild the docker to make easier to rebuild it 

I did not changed the README.md ... 

Again, thanks a lot for your work, it help me a lot. Hope my changes give you good ideas! 

Best regards,

Cássio

2020-09-13 22:37 UTC, gersilex requested changes
Thank you for this. I really love how you turned the `host-trigger-check.sh` into a daemon with an event loop. I would never have thought of that.

Overall this looks really nice and I have added some minor questions and ideas in the review parts.

The environment makes a lot of assumptions (I think it depends on running on GNU/Linux and not having the GNU tools would probably not work, but I will test this later on my RancherOS machines). On the other hand - I think the userbase is quite small right now and probably consists mostly of linux users as Mac OSX users probably don't tinker a lot with apcupsd (please tell me if I'm wrong).

2020-09-13 22:37 UTC, gersilex commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
Should we change this to a sane default like `/etc/apcupsd-docker/scripts.d` or even piggyback into the main apcupsd directory in `/etc/apcupsd/scripts.d` ?

Feels like its own little cool thing that deserves a folder for all possible actions scripts.

2020-09-13 22:37 UTC, gersilex commented on host-trigger-check.sh
> +  IFS="
Can we write this as `IFS=$'\n'` ?

2020-09-13 22:37 UTC, gersilex commented on Dockerfile
> +CMD [ "/sbin/apcupsd", "-b", "&" ]
Is there a reason that you put PID 1 into the background?

2020-09-13 22:37 UTC, gersilex commented on Dockerfile
> +EXPOSE 3551/tcp
This is the port hint used when I connect my UPS directory via USB and to make it available to other hosts, correct?

2020-09-13 22:37 UTC, gersilex commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
Should we issue a warning (no error) when apcupsd fired an action that we have no script for in our `APC_SRC_DIR`?

2020-09-13 22:37 UTC, gersilex commented on host-trigger-check.sh
> +    ./${2}
What about printing an error when the action script exited with non-zero. We can also include the exitcode into the error message. That could help a lot when developing and debugging action scripts.

2020-09-13 22:37 UTC, gersilex commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
Is there a specific reason to not use the unquoted `$*` to forward all those arguments into the `action` function?

2020-09-14 12:03 UTC, cassiorossi commented
> Thank you for this. I really love how you turned the `host-trigger-check.sh` into a daemon with an event loop. I would never have thought of that.
> 
> Overall this looks really nice and I have added some minor questions and ideas in the review parts.
> 
> The environment makes a lot of assumptions (I think it depends on running on GNU/Linux and not having the GNU tools would probably not work, but I will test this later on my RancherOS machines). On the other hand - I think the userbase is quite small right now and probably consists mostly of linux users as Mac OSX users probably don't tinker a lot with apcupsd (please tell me if I'm wrong).

First of all, thanks a lot for your quick answer! Good to hear that you've liked! :)

I will take a look into your feedbacks and answer/change them as soon as possible! 

Best regards,

Cássio Rossi

2020-09-14 12:27 UTC, cassiorossi commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
The $APC_SCR_DIR is a directory in the host machine. The idea was to create an external script location in a way that would be possible to change the "hook action scripts" without rebuilding the docker. 

In my installation I've pointed this location for a /mnt/admin/script/acpupsd with all possible hook scripts (copied from apcupsd original folder) directory that is also under a version control. So if I want to change de shudown behavior, I just need to edit the shudown hook script. However what we can do is check if the APC_SCR_DIR is set, and if it is not set than use a default location as you have suggested (`/etc/apcupsd/scripts.d`). 

What do you think about it?

2020-09-14 12:27 UTC, cassiorossi commented on host-trigger-check.sh
> +  IFS="
Great! Did not know that notation!

2020-09-14 12:28 UTC, cassiorossi commented on Dockerfile
> +CMD [ "/sbin/apcupsd", "-b", "&" ]
That was a test that I run and I forgot to roll it back to the original format. I will review it.

2020-09-14 12:29 UTC, cassiorossi commented on Dockerfile
> +EXPOSE 3551/tcp
That is the port to access the an admin environment via web, but to be honest this is not working. I have to check it better ...

2020-09-14 12:32 UTC, cassiorossi commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
Good point! Can it be a insertion in the log file like /var/log/apcupsd-docker.log ?

2020-09-14 12:33 UTC, cassiorossi commented on host-trigger-check.sh
> +    ./${2}
Good point! Can it be a insertion in the log file like /var/log/apcupsd-docker.log ?

2020-09-14 12:33 UTC, cassiorossi commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
Good point! Can it be a insertion in the log file like /var/log/apcupsd-docker.log ?

2020-09-14 12:36 UTC, cassiorossi commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
The "$*" is used for input args, isn't? Can I use it for local variables?

2020-09-14 15:32 UTC, iwt-leroyfoerster commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
Sounds great!

Did you intend to ship the `env.list` file or should every use create it in order to override the defaults? I like the latter as we could easily set defaults in the script as you mentioned.

2020-09-14 15:38 UTC, iwt-leroyfoerster commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
We should just output it to `stderr` and leave it to the user to redirect it or use it in an init system (like `journalctl` when using systemd).

2020-09-14 15:39 UTC, gersilex commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
Sounds great!

Did you intend to ship the env.list file or should every use create it in order to override the defaults? I like the latter as we could easily set defaults in the script as you mentioned.

2020-09-14 15:39 UTC, gersilex commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
We should just output it to stdout and leave it to the user to redirect it or use it in an init system (like journalctl when using systemd).

2020-09-14 16:47 UTC, cassiorossi commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
Good point you have. Actually I was think in a default value just for the APC_SCR_DIR variable because the other variables, they need to be assigned with specific local IP ... Maybe a simpler solution is to ship the env.list with ACP_SRC_DIR="/etc/apcupsd/scripts.d". I will think if occur me other solution in a meanwhile ....

2020-09-14 16:48 UTC, cassiorossi commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
Ok, deal! Sounds better an more "standard" solution.

2020-09-15 15:15 UTC, gersilex commented on host-trigger-check.sh
> +    ./${2}
I'd do it just like in https://github.com/gersilex/apcupsd-docker/pull/4#discussion_r488032694

2020-09-15 15:16 UTC, gersilex commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
Ah sorry, I didn't realize those were `awk` variables and not shell variables.

2020-09-15 15:23 UTC, gersilex commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
It looks like we only ever use the `event` parameter from apcupsd (which is `$1` inside of `apccontrol` and `$2` here because of the prepended date).

Why no throw all of it away, including the `cDate` and just feed the event name into netcat? That way we wouldn't need any parsin, splitting and the like. If you think we might need it later we can then again discuss a scalable solution for this. What do you think?

2020-09-15 17:49 UTC, cassiorossi commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
I got your point ... I can get date/time in the hook script time .... this was a copy of my old solution. Moving it to a standard solution perspective, in fact, it doesn't make much sense at all.
I will change it, no problem! :)

2020-09-21 00:26 UTC, cassiorossi commented on env.list
> +APC_SCR_DIR="/path/to/acp/scripts"
Changes done, used a default value for ACP_SRC_DIR.

2020-09-21 00:27 UTC, cassiorossi commented on host-trigger-check.sh
> +  IFS="
Applied.

2020-09-21 00:27 UTC, cassiorossi commented on Dockerfile
> +CMD [ "/sbin/apcupsd", "-b", "&" ]
Applied.

2020-09-21 00:27 UTC, cassiorossi commented on Dockerfile
> +EXPOSE 3551/tcp
Applied.

2020-09-21 00:27 UTC, cassiorossi commented on host-trigger-check.sh
> +  if [[ -f ${APC_SCR_DIR}/${2} ]]; then
Applied.

2020-09-21 00:27 UTC, cassiorossi commented on host-trigger-check.sh
> +    ./${2}
Applied.

2020-09-21 00:27 UTC, cassiorossi commented on host-trigger-check.sh
> +      (*) action $P1 $P2 $P3 $P4;;
Applied.

2020-09-21 17:37 UTC, gersilex requested changes
Thank you for your great changes. Found some typos and have some questions :)

2020-09-21 17:37 UTC, gersilex commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Why do we run bash to interpret the script instead of running it (by giving the full path)? I think when we just run it the exit code from the script will properly return and be store in `$?`.

Then line 9 could be like this:
```bash
"${APC_SCR_DIR}/${APC_EVENT}"
RET_CODE=$?
```

Or do I miss something?

2020-09-21 17:37 UTC, gersilex commented on host-trigger-check.sh
> +      echo "[ERROR] host-trigger-check.sh - "$(date +{DATE_MASK})" the apcd hook script for event '${APC_EVENT}' return code '$RET_CODE'"
I think there is a missing $ sign for the variable expansion.

2020-09-21 17:37 UTC, gersilex commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
`pkill -0 host-trigger-check.sh` returns successfully (0 exit code) when it finds a process that contains `host-trigger-check.sh`:

```bash
while pkill -0 host-trigger-check.sh; do
```

I think `killall` can do this as well (remember to use SGINAL 0). Can you check if you have `pkill` or `killall` available and it works for you, too?

2020-09-21 17:37 UTC, gersilex commented on host-trigger-check.sh
> +  IFS="\n"
The dollar sign is important to have bash treat it as escape sequence: `IFS=$'\n'`

https://unix.stackexchange.com/a/184866

2020-09-21 17:46 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
It was like this but it was not working ... when the APC hook script run the "exit 1", it exits the host-trigger-check.sh. I found this notation googling about /bin/bash -e. What I understood was that in other notation, the script was been treated as a include instead of an call. 

Don´t know if you have more information about it. :)

2020-09-21 17:47 UTC, cassiorossi commented on host-trigger-check.sh
> +      echo "[ERROR] host-trigger-check.sh - "$(date +{DATE_MASK})" the apcd hook script for event '${APC_EVENT}' return code '$RET_CODE'"
Yes .. you are right! I will changed it ..

2020-09-21 17:48 UTC, cassiorossi commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
Ow .. great suggestion. I will try it !

2020-09-21 17:48 UTC, cassiorossi commented on host-trigger-check.sh
> +  IFS="\n"
Ok, missed that one! :)

2020-09-21 19:34 UTC, gersilex commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Or including the output of both stderr and stdout:

```sh
SCRIPT_OUTPUT=$("${APC_SCR_DIR}/${APC_EVENT}" 2>&1)
SCRIPT_RETURN_CODE=$?
```

2020-09-21 19:47 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
I will try this way and let you know!

2020-09-21 23:22 UTC, cassiorossi commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
Mmm .. reviewing my code, I remembered that I don't kill the host-trigger-check.sh process, instead I send "quit" message so it can realize a "safe exit". Please let me know if there is something else than that in your point.

2020-09-21 23:49 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Same behavior. The "exit 1" in the commok hook script made the host-trigger-check.sh exit also.  However I think that I achieved something between:

`    cd "${APC_SCR_DIR}"
    ./${APC_EVENT} || RET_CODE=$?
`
That way I think the stdout/stderr will not be merged with the return code. What do you say?

2020-10-07 20:00 UTC, gersilex reviewed
urgh I forgot to submit the review. Sorry for keeping you waiting so long.

2020-10-07 20:07 UTC, gersilex commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
I don't understand why we would change the working directory to the APC_SRC_DIR instead of running it directly. Also in the example RET_CODE would be unset if the exit code is zero.

The `exit 1` really should not be propagated to `host-trigger-check.sh`. This should only happen if we `source` the file, which we don't. Can you show me your commok script?

2020-10-07 21:36 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Yes, I don't have a answer for that. What I am experiencing is if I don't do it this way, it works like an "import" and the "exit" in the `APC_EVENT` exits the `host-trigger-check.sh`   

This is my commok scritp that I am using as test:

```
#!/bin/sh
. $HOME_CROSSI_SRC/.set_src_env.sh

$HOME_CROSSI_SRC/send_INFO.ksh "COMOK: Communication with UPS is back" 

exit 0
```

2020-10-07 21:47 UTC, cassiorossi commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
I got your point, my idea is not kill the `host-trigger-check.sh` but send a special message to the fifo that is being read by the loop `while read -r APCD_EVENT <&"${COPROC[0]}"; do` ... once that loop reads the "quit" string, it breaks the loop `('quit') break ;;` and then it kill only the nc server `kill "$COPROC_PID" 2>&1 1> /dev/null` and the `host-trigger-check.sh` ends.

The loop `while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do` should never runs more than once. This will runs twice only in a fail situation that makes while `host-trigger-check.sh` started duplicated.

Sorry if I taking too long into that item, but I just want to make sure that we are with the same understand. :)

2020-10-07 21:47 UTC, cassiorossi commented on Dockerfile
> +CMD [ "/bin/sh", "-c", "/entryPoint.sh" ]
Sure, I will try that way. :)

2020-10-08 13:18 UTC, gersilex commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Oh it just dawns to me that it might be the `-e` in https://github.com/gersilex/apcupsd-docker/blob/a41a388a0af9d664599358bf49462936b85fa841/host-trigger-check.sh#L1 

While this is really useful, the `-e` will exit the script on any unhandeled error. Try removing the `-e` and use it like in https://github.com/gersilex/apcupsd-docker/pull/4#discussion_r492298974

I can totally live without the `-e` for now.

2020-10-08 13:22 UTC, gersilex commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
I understand what you are doing and try to tell how `ps -ef | grep host-trigger-check.sh | grep -v grep` and `pkill -0 host-trigger-check.sh` does exactly the same.

In the end, it doesn't even matter and both will work, so let's just leave that for now :smile:

2020-10-10 00:51 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
In fact I didn't try it yet. I will try and let u know!

2020-10-10 01:03 UTC, cassiorossi commented on host-trigger-check.sh
> +  while ps -ef | grep host-trigger-check.sh | grep -v grep > /dev/null ; do
😅 ... I suppose that I really not getting the point of this approach. Agree w/ u: Let's move on and latter we can visit this improvement again. 👍😊

2020-10-11 14:51 UTC, gersilex commented on host-trigger-check.sh
> +	#!/bin/bash
whoops, looks like this whitespace slipped in there

2020-10-11 14:54 UTC, gersilex commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Does it work without the `-e` ? :)

2020-10-11 14:55 UTC, cassiorossi commented on host-trigger-check.sh
> +	#!/bin/bash
Ops! 😁

2020-10-11 15:09 UTC, cassiorossi commented on host-trigger-check.sh
> +    RET_CODE=$(/bin/bash "${APC_SCR_DIR}/${APC_EVENT}" || echo $?)
Yep! actually, I found it in the bash man entry:


-```
e      Exit immediately if a pipeline  (which  may
                      consist  of  a  single  simple  command), a
                      list, or  a  compound  command  (see  SHELL
                      GRAMMAR  above), exits with a non-zero sta‐
                      tus.  The shell does not exit if  the  com‐
                      mand that fails is part of the command list
                      immediately following a while or until key‐
                      word,  part of the test following the if or
                      elif reserved words, part  of  any  command
                      executed in a && or || list except the com‐
                      mand following the final && or ||, any com‐
                      mand  in a pipeline but the last, or if the
                      command's return value  is  being  inverted
                      with !.  If a compound command other than a
                      subshell returns a non-zero status  because
                      a   command   failed  while  -e  was  being
                      ignored, the shell does not exit.   A  trap
                      on  ERR,  if  set,  is  executed before the
                      shell exits.  This option  applies  to  the
                      shell  environment  and each subshell envi‐
                      ronment separately (see  COMMAND  EXECUTION
                      ENVIRONMENT above), and may cause subshells
                      to exit before executing all  the  commands
                      in the subshell.
```

2020-10-12 01:20 UTC, gersilex approved these changes

2020-10-12 01:22 UTC, gersilex commented
We have come a long way and you added a lot of features. Thank you so much for extending the software!

I'll open a new issue for updating the Readme and we can tackle this whenever we feel like it.

2020-10-12 01:23 UTC, merged

2020-10-12 13:05 UTC, cassiorossi commented
Leroy,

It was a great experience to work with you in this interaction. Learned a
lot with it. So, thanks a lot for it!

Let's keep improving the project!

Best regards,

Cássio Rossi


Em dom, 11 de out de 2020 22:22, Leroy Förster <notifications@github.com>
escreveu:

> We have come a long way and you added a lot of features. Thank you so much
> for extending the software!
>
> I'll open a new issue for updating the Readme and we can tackle this
> whenever we feel like it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gersilex/apcupsd-docker/pull/4#issuecomment-706806077>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACTHG7NA4PVDIBTVOEGOPQLSKJK5HANCNFSM4RK36EMQ>
> .
>